# reminder
# Author: Francesco Pischedda <francesco@pischedda.info>

* Reminder

** Introduction
*** Project description

 Periodically send reminders to friends/colleagues until they decide it is time
 to help you with whatever you requested them...or until you lose their
 friendship...

 Users should be able to send reminders via email at least, other kind of
 receivers such as IM systems, SMS, mobile or other forms of notifications
 could be added in the future.

 The frequency of the reminder should be configurable by the user that creates
 it; it should be possible to disable the reminder manually (both by the receiver
 and the creator) or automatically by integrating with third party notification
 systems.

 To create a reminder a user should be logged in in the system but to mark a
 reminder as completed (or acknowledged) a user might only need a "magic link",
 received in a notification generated by the reminder; this needs to be like that
 because recipients of reminder notifications may not be logged in or even
 registered in the platform.

** User stories

*** Registration

 As a Anonymous User I want to create an account to create and send reminders.
 I will provide a valid email address and password and I expect to receive a
 confirmation email containing an activation code; after my account will be
 activated I will be able to use the service.

*** Login

 As a Registered User I want to have access to my reminders and my profile.
 I will provide my login credentials, an email and the corresponding password,
 and if the operation will be successful I can access my reminders and create
 new ones.

*** Create a reminder

 As a LoggedIn User I want to create a reminder to notify my recipients about
 an important thing I may have asked or which I expect from them; in the
 reminder I want to specify a brief description of what the reminder is about,
 the list of recipients, specifying their email or other ways to reach them,
 and a frequency (how often the reminder should be notified to the recipients)

*** Manage a reminder

 As a LoggedIn User and Reminder Owner I want to be able to modify, close or
 delete one Reminder.

*** Acknowledge a reminder

 As a Reminder Recipient I want to acknowledge a Reminder, meaning that the
 requested action have been completed.

*** Comment a reminder

 As a Reminder Recipient or LoggedIn Reminder Owner I want to add comment to
 the Reminder; this may be done because I need more information to complete
 what have been asked in the Reminder or maybe because the work cannot be
 completed, or other reasons.

** Implementation

 The project is implemented as a RESTful backend and eventually a web based
 frontend on top of it; this decision have been made to make it possible to
 have multiple frontends backed by the same backend application.

*** REST APIs layout

  - auth
  - reminders
